### ISSUE TITLE
Add ability for calling navigate without changing the URL.

### ISSUE THREAD

**Issue by athiwatc** [nlessmann/Simrou#2]
In a more complex system where you use the routing for everything logic some thing like "router.call('/delete/something')" could be useful.

**Comment by nlessmann** [comment]
Hi,

thanks for the input! I'm not sure if this is what you're looking for, but there already is `resolve(url, method)` - calling this method travels trough all registered routes looking for a match without touching "location.hash".

I'm gonna add this to the readme.

**Comment by athiwatc** [comment]
Thanks, this is exactly what I'm looking for.
