### ISSUE TITLE
router.start() doesn't work in Safari / Safari mobile

### ISSUE THREAD

**Issue by djgrant** [nlessmann/Simrou#5]
When using router.start('/myroute'); the route is not registered in Safari's history.

To reproduce in demo files navigate to article 172 then click the browser back button. 

Expected behaviour: browser goes to overview.html#/homepage

Behaviour in Safari: browser goes to overview.html

**Comment by nlessmann** [comment]
Thanks for your input, I'm looking into this. That's really some weird behavior...

**Comment by nlessmann** [comment]
Would you mind giving it a try with this updated version?
https://raw.github.com/buero-fuer-ideen/Simrou/dev/build/simrou.min.js

**Comment by djgrant** [comment]
Thanks for resolving this so quickly. Works perfectly.
