### ISSUE TITLE
Enable in IE7

### ISSUE THREAD

**Issue by djgrant** [nlessmann/Simrou#6]
How can simrou be enabled in IE7? The URL is appended but the action handler not called.

**Comment by nlessmann** [comment]
There is a tiny note about that at the very bottom of the Readme.md file - IE7 does not support the "onhashchange" event, therefore you will need to simulate it in order to get Simrou working properly in that browser. Ben Alman's jQuery Plugin is an excellent choice for this task: http://benalman.com/projects/jquery-hashchange-plugin/

**Comment by djgrant** [comment]
I did attempt to use the hashchange plugin without any setup. Although this seems to add support for the onhashchange event an error is throw up by IE7:
'originalEvent.newURL' is null or not an object.
Line: 7, Char 146

Tested using Simrou demo.

**Comment by nlessmann** [comment]
Very helpful, thank you! I've tried to fix this issue (the simulated event does not provide the "newURL" parameter) - but there was a reason to use this to begin with: When the hash changes very quickly (e.g. first to #a, then to #b), the value of `document.location.hash` may sometimes already be #b when the onhashchange event that got triggered by the change to #a reaches the event handler.

So there still might (in some rare cases) be some stability issues in IE < 8, but they can not be resolved.

It would be great if you could test again and report:
https://raw.github.com/buero-fuer-ideen/Simrou/dev/build/simrou.min.js

**Comment by djgrant** [comment]
I have tried v1.3. Action handlers are not called in IE7 or Chrome.

In Chrome I get the following error:
Uncaught TypeError: Cannot call method 'slice' of null simrou.min.js 
Line 10

IE7 shows no errors until back button is clicked:
'null' is null or not an object 
Line 11
Char 341

**Comment by nlessmann** [comment]
Thanks again, this was a really stupid bug that appeared first in v1.3, but had nothing to do with the original issue - no idea how I could have missed that. Should be all working now with v1.3.1 (at least, it does for me).

**Comment by djgrant** [comment]
Works perfectly. Thanks!
